### PR TITLE
fix return value for FIPS arch check

### LINKED ISSUE #98: split _fips_prep_check() checks so that the exit status is correct
Currently the `_fips_prep_check` function performs two very different checks:

- if the current CPU has the minimum flags
- if the packages are already installed

In both cases, it returns 1, which is interpreted as a failure. The whole script then, however, returns 6, which according to the man page means:

`6      It was determined that FIPS has already been installed`

That is incorrect if what failed was the cpu flags check. We should probably move the first check into the new `check_service_support` changed in PR #95 so that we can exit 7 (also introduced in that PR).

### PR DESCRIPTION
**Pull request by albertodonato**
Fixes #98

### CODE REVIEW

File: modules/service-fips.sh [hunk 1]
```diff
@@ -107,11 +109,11 @@ _fips_prep_check() {
...
 
-    # check to see if fips pkgs already installed.
-    fips_hmacs="openssh-client-hmac openssh-server-hmac libssl1.0.0-hmac \
-                linux-fips strongswan-hmac"
-    for pkg in $fips_hmacs; do
+_fips_check_packages_installed() {
+    local pkg
+    for pkg in $FIPS_HMAC_PACKAGES; do
         if is_package_installed "$pkg"; then
             if fips_is_enabled; then
```
Comment (panlinux) [inline modules/service-fips.sh]: I know this wasn't changed in this branch, but I think this check should be better. It should check that all packages are installed before moving on to fips_is_enabled, because if there is a missing package, we will want to fix it by installing it. And we definitely shouldn't tell the user to reboot if we find out just one package is installed and not the rest.

File: modules/service-fips.sh [hunk 2]
```diff
@@ -47,10 +49,11 @@ fips_is_enabled() {
 fips_check_support() {
     check_service_support \
         "Canonical FIPS 140-2 Modules" "$FIPS_SUPPORTED_SERIES" \
-        "$FIPS_SUPPORTED_ARCHS"
+        "$FIPS_SUPPORTED_ARCHS" || return 1
```
Comment (panlinux) [inline modules/service-fips.sh]: check_service_support() just exits (4 or 7), this return 1 is for a "just in case" scenario? Maybe we should change check_service_support() to return 4 or 7 instead if exiting?

File: modules/service-fips.sh [hunk 3]
```diff
@@ -88,9 +91,8 @@ _fips_enabled_check() {
     echo 0
 }
 
-_fips_prep_check() {
-    local fips_hmacs pkg power_cpu_ver
-
+_fips_check_arch() {
+    local power_cpu_ver
```
Comment (panlinux) [inline modules/service-fips.sh]: I'm thinking _fips_check_arch() should return 7 in the case of failure, or its call in fips_check_support() should || return 7

File: modules/service-fips.sh (hunk 1 above)
Comment (albertodonato) [reply modules/service-fips.sh]: Can you file a separate bug for this?

Comment (panlinux) [reply modules/service-fips.sh]: Sure, issue #102

File: modules/service-fips.sh (hunk 3 above)
Comment (albertodonato) [reply modules/service-fips.sh]: good catch, done

File: modules/service-fips.sh (hunk 2 above)
Comment (albertodonato) [reply modules/service-fips.sh]: ah, I think this was a leftover, removed the `|| return 1`
